name: CI-COVER-DATABASES

on:
#   push:
#     paths:
#       - '**.py'
#       - '.github/workflows/**'
#       - '!dev/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.10"

    name: Check Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build the stack
        run: docker-compose up -d mysql postgres #presto trino clickhouse vertica

      - name: Install Poetry
        run: pip install poetry

      - name: Install package
        run: "poetry install"

      - name: Run unit tests
        env:
            # PRESTO_URI: 'presto://presto@127.0.0.1/postgresql/public'
            # TRINO_URI: 'trino://postgres@127.0.0.1:8081/postgresql/public'
            # CLICKHOUSE_URI: 'clickhouse://clickhouse:Password1@localhost:9000/clickhouse'
            # VERTICA_URI: 'vertica://vertica:Password1@localhost:5433/vertica'
            # SNOWFLAKE_URI: '${{ secrets.SNOWFLAKE_URI }}'
            # REDSHIFT_URI: '${{ secrets.REDSHIFT_URI }}'
        run: |
          docker ps
          docker network inspect local
          docker logs mysql
          poetry run unittest-parallel